name: pull,rebuild, restart

on:
  push:
    branches: [main]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd bleghdit
            git pull
            npm install
            npx tsc
            pm2 stop all
            pm2 delete all
            pm2 start --name "server" npm -- start
            cd client
            npm install
            npm run build
            pm2 start --name "client" npm -- start
            
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
