name: pull,rebuild, restart

on:
  push:
    branches: [main]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd leddit
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            node --version
            npm --version
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
