name: pull,rebuild, restart

on:
  push:
    branches: [main]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd leddit
            ls
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
