name: pull,rebuild, restart

on:
  push:
    branches: [main]


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd bleghdit
            git pull
            npm install
            npx tsc
            cd client
            npm install
            npm run build
            pm2 restart all
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
